name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - uses: calcit-lang/setup-cr@0.0.8

    - name: "test"
      run: env=ci cr -1

    - name: "test js"
      run: >
        cr -1 js
        && yarn && node main.mjs
