name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a2/cr'
        name: 'cr'
        version: '0.7.0-a2'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a2/caps'
        name: 'caps'
        version: '0.7.0-a2'

    - name: "test"
      run: env=ci cr --once

    - name: "test js"
      run: >
        cr --emit-js --once
        && yarn && node main.mjs
